---
title: "Assignment 1 - Data 1204"
output:
  pdf_document: default
  word_document: default
---
Install required packages
install.packages(c("lattice", "psych", "gmodels", "readr", "ggplot2"))

```{r}
library(lattice)
library(psych)
library(gmodels)
library(readr)
library(ggplot2)
```

Loading cars db data

```{r}
cars_db <- read.csv("carsDB.csv")
cars_db
```

```{r}
ggplot(data = cars_db, aes(x=disp, y=mpg)) + geom_point(color = "#000000") + 
  geom_smooth(formula = y~x, method = 'loess', color = "#154083") +
  labs(title = "Comparing Fuel Efficiency to Displacement",
       subtitle = "Relationship between the engine's fuel efficiency and its displacement for \ndifferent car models",
       x = "Displacement (cubic inches)",
       y = "Fuel Efficiency (miles per gallon)")
ggsave("mpg_vs_disp.png", dpi = 1200)
```

```{r}
ggplot(data = cars_db, aes(x=hp, y=mpg)) + geom_point(color = "#000000") + 
  geom_smooth(formula = y~x, method = 'loess', color = "#154083") +
  labs(title = "Comparing Fuel Efficiency to Horsepower",
       subtitle = "Relationship between the engine's fuel efficiency and its theoretical power output \nfor different car models",
       x = "Gross Horsepower (hp)",
       y = "Fuel Efficiency (miles per gallon)")
ggsave("mpg_vs_hp.png", dpi = 1200)
```
```{r}
ggplot(data = cars_db, aes(x=wt, y=mpg)) + geom_point(color = "#000000") +
  geom_smooth(formula = y~x, method = 'loess', color = "#154083") +
  labs(title = "Comparing Fuel Efficiency to Weight of the Car",
       subtitle = "Relationship between the engine's fuel efficiency and the overall weight of the car \nfor different car models",
       x = "Weight (lb/1000)",
       y = "Fuel Efficiency (miles per gallon)")
ggsave("mpg_vs_wt.png", dpi = 1200)
```
